operations:
  url: "http://bb-operations.mifos.io/api/v1"

identity:
  channel:
    clients:
      - clientId: mifos
        clientSecret: password
        tenant: gorilla
      - clientId: mifos
        clientSecret: password
        tenant: lion