operations:
  url: "http://bb-operations.mifos.io/api/v1"

identity:
  channel:
    clients:
      - clientId: channel-gorilla
        clientSecret: p1234
        tenant: gorilla
      - clientId: channel-lion
        clientSecret: p1234
        tenant: lion